/*
*	全国三级城市联动 js版
*/
function Dsy(){
    this.Items = {};
}
Dsy.prototype.add = function(id,iArray){
    this.Items[id] = iArray;
}
Dsy.prototype.Exists = function(id){
    if(typeof(this.Items[id]) == "undefined") return false;
    return true;
}

function change(v){
    var str="0";
    for(i=0;i<v;i++){
        str+=("_"+(document.getElementById(s[i]).selectedIndex-1));
    };
    var ss=document.getElementById(s[v]);
    with(ss){
        length = 0;
        options[0]=new Option(opt0[v],opt0[v]);
        if(v && document.getElementById(s[v-1]).selectedIndex>0 || !v){
            if(dsy.Exists(str)){
                ar = dsy.Items[str];
                for(i=0;i<ar.length;i++){
                    options[length]=new Option(ar[i],ar[i]);
                }//end for
                if(v){ options[0].selected = true; }
            }
        }//end if v
        if(++v<s.length){change(v);}
    }//End with
}

var dsy = new Dsy();
dsy.add("0",["BALI","BANGKA BELITUNG","BANTEN","BENGKULU", "D.I. YOGYAKARTA","DKI JAKARTA","JAMBI","JAWA BARAT","JAWA TENGAH","JAWA TIMUR","KALIMANTAN BARAT","KALIMANTAN SELATAN","KALIMANTAN TENGAH","KALIMANTAN TIMUR","KEPULAUAN RIAU","LAMPUNG","NANGGROE ACEH DARUSSALAM","NUSA TENGGARA BARAT","RIAU","SULAWESI SELATAN","SUMATERA BARAT","SUMATERA SELATAN","SUMATERA UTARA"]);

dsy.add("0_0",["BADUNG","BANGLI","BULELENG","DENPASAR","GIANYAR","JEMBRANA","KARANG ASEM","KLUNGKUNG","TABANAN"]);
dsy.add("0_0_0",["ABIANSEMAL","KUTA","KUTA SELATAN","KUTA UTARA","MENGWI","PETANG"]);
dsy.add("0_0_1",["BANGLI","KINTAMANI","SUSUT","TEMBUKU"]);
dsy.add("0_0_2",["BANJAR-SGA","BULELENG","BUSUNG BIU","GEROKGAK","KUBUTAMBAHAN","SAWAN","SERIRIT","SINGARAJA","SUKASADA","TEJAKULA"]);
dsy.add("0_0_3",["BADUNG","DENPASAR BARAT","DENPASAR SELATAN","DENPASAR TIMUR","DENPASAR UTARA","JIMBARAN","NGURAH RAI","NUSA DUA","ULUWATU"]);
dsy.add("0_0_4",["BELAH BATUH","GIANYAR","PAYANGAN","SUKAWATI","TAMPAK SIRING","TEGALLALANG","UBUD"]);
dsy.add("0_0_5",["JEMBRANA","MELAYA","MENDOYO","NEGARA","PEKUTATAN"]);
dsy.add("0_0_6",["ABANG","AMLAPURA","BEBANDEM","KARANG ASEM","KUBU-APU","MANGGIS","RENDANG","SELAT-APU","SIDEMEN"]);
dsy.add("0_0_7",["BANJARANGKAN","DAWAN","KLUNGKUNG","NUSAPEDINA"]);
dsy.add("0_0_8",["BATURITI","KEDIRI-TNW","KERAMBITAN","MARGA","PENEBEL","PUPUAN","SELEMADEG","SELEMADEG BARAT","SELEMADEG TIMUR","TABANAN"]);
dsy.add("0_1",["BANGKA","BANGKA BARAT","BANGKA SELATAN","BANGKA TENGAH","BELITUNG","BELITUNG TIMUR","PANGKAL PINANG"]);
dsy.add("0_1_0",["BELINYU","SUNGAI LIAT"]);
dsy.add("0_1_1",["AIR BELO","AIR LIMAU","BELO LAUT","JEBUS","KELAPA","PARITIGA","SIMPANG TERITIP","SUNGAI BARU","SUNGAI DAENG","TANJUNG-MEK","TEMPILANG"]);
dsy.add("0_1_2",["TOBOALI"]);
dsy.add("0_1_3",["KOBA"]);
dsy.add("0_1_4",["BADAU-TJQ","MEMBALONG","SELAT NASIK","SIJUK","TANJUNG PANDAN"]);
dsy.add("0_1_5",["DAMAR","DENDANG-MAG","GANTUNG","KELAPA KAMPIT","MANGGAR","SIMPANG PESAK","SIMPANG RENGGIANG"]);
dsy.add("0_1_6",["BUKIT INTAN","GABEK","GERUNGGANG","PANGKAL BALAM","RANGKUI","TAMAN SARI-PGK"]);
dsy.add("0_2",["BALARAJA","CILEGON","CIPUTAT","KAB.SERANG","LEBAK","PANDEGLANG","SERANG","TANGERANG"]);
dsy.add("0_2_0",["BALARAJA","CIKUPA","CISAUK","CISOKA","CURUG-BAL","GUNUNG KALER","JAMBE","JAYANTI","KELAPA DUA","KEMIRI-BAL","KOSAMBI","KRESEK","KRONJO","LEGOK","MAUK","MEKAR BARU","PAGEDANGAN","PAKUHAJI","PANONGAN","PASAR KEMIS","RAJEG","SEPATAN","SEPATAN TIMUR","SINDANG JAYA","SOLEAR","SUKA DIRI","SUKAMULYA","TELUK NAGA","TIGARAKSA"]);
dsy.add("0_2_1",["CIBEBER-CIL","CILEGON","CITANGKIL","CIWANDAN","GEROGOL","JOMBANG-CIL","PULO MERAK","PURWAKARTA-CIL"]);
dsy.add("0_2_2",["CIPUTAT","CIPUTAT TIMUR","PAMULANG","PONDOK AREN","SERPONG","SERPONG UTARA","SETU-CIP"]);
dsy.add("0_2_3",["ANYAR","BANDUNG-SNG","BAROS-SNG","BINUANG-SNG","BOJONEGARA","CARENANG","CIKANDE","CIKEUSAL","CINANGKA","CIOMAS-SNG","CIRUAS","GUNUNG SARI","JAWILAN","KIBIN","KOPO","KRAGILAN","KRAMATWATU","LEBAK WANGI","MANCAK","PABUARAN-SNG","PADARINCANG","PAMARAYAN","PETIR","PONTANG","PULO AMPEL","TANARA","TIRTAYASA","TUNJUNG TEJA","WARINGIN KURUNG"]);
dsy.add("0_2_4",["BANJARSARI-RKS","BAYAH","BOJONGMANIK","CIBADAK-RKS","CIBEBER-RKS","CIGEMBLONG","CIHARA","CIJAKU","CIKULUR","CILELES","CILOGRANG","CIMARGA","CIPANAS-RKS","CIRINTEN","CURUGBITUNG","GUNUNG KENCANA","KALANG ANYAR","LEBAK GEDONG","LEUWI DAMAR","MAJA-RKS","MALINGPING","MUNCANG","PANGGARANGAN","RANGKAS BITUNG","SAJIRA","SOBANG-RKS","WANASALAM","WARUNG GUNUNG"]);
dsy.add("0_2_5",["ANGSANA-PGL","BANJAR-PGL","BOJONG-PGL","CADASARI","CARITA","CIBALIUNG","CIBITUNG-PGL","CIGEULIS","CIKEDAL","CIKEUSIK","CIMANGGU-PGL","CIMANUK","CIPEUCANG","CISATA","JIPUT","KADU HEJO","KARANG TANJUNG","KORONCONG","LABUAN-PGL","MAJASARI","MANDALA WANGI","MEKARJAYA","MENES","MUNJUL","PAGELARAN-PGL","PANDEGLANG","PANIMBANG","PATIA","PICUNG","PULOSARI-PGL","SAKETI","SINDANG RESMI","SOBANG-PGL","SUKARESMI-PGL","SUMUR"]);
dsy.add("0_2_6",["CIPOCOK JAYA","CURUG-SEG","KASEMEN","SERANG","TAKTAKAN","WALANTAKA"]);
dsy.add("0_2_7",["BATU CEPER","BENDA","CIBODAS","CILEDUG-TGR","CIPONDOH","JATIUWUNG","KARANG TENGAH-TGR","KARAWACI","NEGLASARI","PERIUK","PINANG","TANGERANG"]);
dsy.add("0_3",["ARGAMAKMUR","BENGKULU","KEPAHIANG","LUBUK LINGGAU","REJANG LEBONG"]);
dsy.add("0_3_0",["AIR BESI","AIR NAPAL","AIR PADANG","ARGA MAKMUR","ARMA JAYA","BATIK NAU","GIRI MULIA","KERKAP","KETAHUN","LAIS-ARG","PUTRI HIJAU"]);
dsy.add("0_3_1",["GADING CEMPAKA","KAMPUNG MELAYU","MUARA BANGKAHULU","RATU AGUNG","RATU SAMBAN","SELEBAR","SINGARAN PATI","SUNGAI SERUT","TELUK SEGARA"]);
dsy.add("0_3_2",["BERMANI ILIR","KABAWETAN","KEPAHIANG","MERIGI","TEBAT KARAI","UJAN MAS-KPA"]);
dsy.add("0_3_3",["LUBUK LINGGAU BARAT 1","LUBUK LINGGAU BARAT 2","LUBUK LINGGAU SELATAN I","LUBUK LINGGAU SELATAN II","LUBUK LINGGAU TIMUR 1","LUBUK LINGGAU TIMUR 2","LUBUK LINGGAU UTARA 2","LUBUK LINGGAU UTARA I"]);
dsy.add("0_3_4",["BERMANI ULU","CURUP","CURUP SELATAN","CURUP TENGAH","CURUP TIMUR","CURUP UTARA","SELUPU REJANG","SINDANG KELINGI"]);
dsy.add("0_4",["BANTUL","KULON PROGO","SLEMAN","WONOSARI","YOGYAKARTA"]);
dsy.add("0_4_0",["BAMBANGLIPURO","BANGUNTAPAN","BANTUL","DLINGO","IMOGIRI","JETIS-BTL","KASIHAN","KRETEK","PAJANGAN","PANDAK","PIYUNGAN","PLERET","PUNDONG","SANDEN","SEDAYU","SEWON","SRANDAKAN"]);
dsy.add("0_4_1",["GALUR","GIRIMULYO","KALIBAWANG-KLP","KOKAP","LENDAH","NANGGULAN","PANJATAN","PENGASIH","SAMIGALUH","SENTOLO","TEMON","WATES-KLP"]);
dsy.add("0_4_2",["BERBAH","CANGKRINGAN","DEPOK-SLM","GAMPING","GODEAN","KALASAN","MINGGIR","MLATI","MOYUDAN","NGAGLIK","NGEMPLAK-SLM","PAKEM-SLM","PRAMBANAN-SLM","SEYEGAN","SLEMAN","TEMPEL","TURI-SLM"]);
dsy.add("0_4_3",["GEDANGSARI","GIRISUBO","KARANGMOJO","NGAWEN-WNO","NGLIPAR","PALIYAN","PANGGANG","PATUK","PLAYEN","PONJONG","PURWOSARI-WNO","RONGKOP","SAPTOSARI","SEMANU","SEMIN","TANJUNGSARI-WNO","TEPUS","WONOSARI-WNO"]);
dsy.add("0_4_4",["DANUREJAN","GEDONG TENGEN","GONDOKUSUMAN","GONDOMANAN","JETIS-JOG","KOTAGEDE","KRATON-JOG","MANTRIJERON","MERGANGSAN","NGAMPILAN","PAKUALAMAN","TEGALREJO-JOG","UMBULHARJO","WIROBRAJAN"]);
dsy.add("0_5",["JAKARTA"]);
dsy.add("0_5_0",["CAKUNG","CEMPAKA PUTIH","CENGKARENG","CILANDAK","CILINCING","CIPAYUNG-JKT","CIRACAS","DUREN SAWIT","GAMBIR","GROGOL PETAMBURAN","JAGAKARSA","JATINEGARA-JKT","JOHAR BARU","KALIDERES","KAMAL-JKT","KEBAYORAN BARU","KEBAYORAN LAMA","KEBON JERUK","KELAPA GADING","KEMAYORAN","KEMBANGAN","KEPULAUAN SERIBU SELATAN","KOJA","KRAMAT JATI","MAKASAR","MAMPANG PRAPATAN","MATRAMAN","MENTENG","PADEMANGAN","PALMERAH","PANCORAN","PASAR MINGGU","PASAR REBO","PENJARINGAN","PESANGGRAHAN-JKT","PULO GADUNG","SAWAH BESAR","SENEN","SETIABUDI","TAMAN SARI-JKT","TAMBORA","TANAH ABANG-JKT","TANJUNG PRIOK","TEBET"]);
dsy.add("0_6",["BANGKO","BATANG HARI","JAMBI","SAROLANGUN","SUNGAI PENUH"]);
dsy.add("0_6_0",["BANGKO-BAO"]);
dsy.add("0_6_1",["MUARA BULIAN"]);
dsy.add("0_6_2",["DANAU TELUK","JAMBI SELATAN","JAMBI TIMUR","JELUTUNG","KOTA BARU-DJB","PASAR JAMBI","PELAYANGAN","TELANAIPURA"]);
dsy.add("0_6_3",["PASAR SAROLANGUN","SAROLANGUN"]);
dsy.add("0_6_4",["SUNGAI PENUH"]);
dsy.add("0_7",["BANDUNG","BANJAR","BEKASI","BOGOR","CIAMIS","CIANJUR","CIBINONG","CIKAMPEK","CIKARANG","CIMAHI","CIREBON","DEPOK","GARUT","INDRAMAYU","KARAWANG","KUNINGAN","MAJALENGKA","NGAMPRAH","PANGANDARAN","PELABUHAN RATU","PURWAKARTA","SINGAPARNA","SOREANG","SUBANG","SUKABUMI","SUMBER","SUMEDANG","TASIKMALAYA"]);
dsy.add("0_7_0",["ANDIR","ANTAPANI","ARCAMANIK","ASTANA ANYAR","BABAKAN CIPARAY","BANDUNG KIDUL","BANDUNG KULON","BANDUNG WETAN","BATU NUNGGAL","BOJONGLOA KALER","BOJONGLOA KIDUL","BUAH BATU","CIBEUNYING KALER","CIBEUNYING KIDUL-BDO","CIBIRU","CICENDO","CIDADAP-BDO","CINAMBO","COBLONG","GEDE BAGE","KIARACONDONG","LENGKONG-BDO","MANDALA JATI","PANYILEUKAN","RANCASARI","REGOL","SUKAJADI-BDO","SUKASARI-BDO","SUMUR BANDUNG","UJUNG BERUNG"]);
dsy.add("0_7_1",["BANJAR-BJA","BANJARSARI-BJA","CIMARAGAS","CISAGA","LAKBOK","LANGENSARI","PAMARICAN","PATARUMAN","PURWAHARJA","RANCAH"]);
dsy.add("0_7_2",["BABELAN","BANTAR GEBANG","BEKASI BARAT","BEKASI SELATAN","BEKASI TIMUR","BEKASI UTARA","CIBITUNG-BKI","JATI ASIH","JATI SAMPURNA","MEDAN SATRIA","MUARA GEMBONG","MUSTIKA JAYA","PONDOK GEDE","PONDOK MELATI","RAWA LUMBU","SETU-BKI","SUKAWANGI","TAMBUN SELATAN","TAMBUN UTARA","TARUMA JAYA"]);
dsy.add("0_7_3",["BOGOR BARAT","BOGOR SELATAN","BOGOR TENGAH","BOGOR TIMUR","BOGOR UTARA","TANAH SEREAL"]);
dsy.add("0_7_4",["BANJARSARI","BAREGBEG","CIAMIS","CIDOLOG-CMI","CIHAURBEUTI","CIJEUNGJING","CIKONENG","CIPAKU","JATINAGARA","KAWALI","LUMBUNG","PANAWANGAN","PANJALU","PANUMBANGAN","PURWADADI-CMI","RAJADESA","SADANANYA","SINDANGKASIH","SUKADANA-CMI","SUKAMANTRI","TAMBAKSARI-CMI"]);
dsy.add("0_7_5",["AGRABINTA","BOJONG PICUNG","CAMPAKA MULYA","CAMPAKA-CJR","CIANJUR","CIBEBER-CJR","CIBINONG-CJR","CIDAUN","CIJATI","CIKADU","CIKALONG KULON","CILAKU","CIPANAS-CJR","CIRANJANG","CUGENANG","GEKBRONG","HAURWANGI","KADUPANDAK","KARANG TENGAH-CJR","LELES-CJR","MANDE","NARINGGUL","PACET-CJR","PAGELARAN-CJR","PASIRKUDA","SINDANGBARANG","SUKALUYU","SUKANAGARA","SUKARESMI-CJR","TAKOKAK","TANGGEUNG","WARUNG KONDANG"]);
dsy.add("0_7_6",["BABAKAN MADANG","BOJONGGEDE","CARINGIN-CIB","CARIU","CIAMPEA","CIAWI-CIB","CIBINONG-CIB","CIBUNGBULANG","CIGOMBONG","CIGUDEG","CIJERUK","CILEUNGSI","CIOMAS-CIB","CISARUA-CIB","CISEENG","CITEUREUP","DRAMAGA","GUNUNG PUTRI","GUNUNG SINDUR","JASINGA","JONGGOL","KEMANG","KLAPA NUNGGAL","LEUWILIANG","LEUWISADENG","MEGA MENDUNG","NANGGUNG","PAMIJAHAN","PARUNG","PARUNG PANJANG","RANCA BUNGUR","RUMPIN","SUKAJAYA-CIB","SUKAMAKMUR","SUKARAJA-CIB","TAJUR HALANG","TAMANSARI-CIB","TANJUNGSARI-CIB","TENJO","TENJOLAYA"]);
dsy.add("0_7_7",["CIKAMPEK","KOTA BARU-CKP","LEMAH ABANG"]);
dsy.add("0_7_8",["BOJONGMANGU","CABANGBUNGIN","CIBARUSAH","CIKARANG BARAT","CIKARANG PUSAT","CIKARANG SELATAN","CIKARANG TIMUR","CIKARANG UTARA","KARANG BAHAGIA","KEDUNGWARINGIN","PEBAYURAN","SERANG BARU","SUKAKARYA-CKR","SUKATANI-CKR","TAMBELANG"]);
dsy.add("0_7_9",["CIMAHI SELATAN","CIMAHI TENGAH","CIMAHI UTARA"]);
dsy.add("0_7_10",["HARJAMUKTI","KEJAKSAN","KESAMBI","LEMAH WUNGKUK","PEKALIPAN"]);
dsy.add("0_7_11",["BEJI-DPK","BOJONGSARI-DPK","CILODONG","CIMANGGIS","CINERE","CIPAYUNG-DPK","LIMO","PANCORAN MAS","SAWANGAN-DPK","SUKMAJAYA","TAPOS"]);
dsy.add("0_7_12",["BANJARWANGI","BANYURESMI","BAYONGBONG","BLUBUR LIMBANGAN","BUNGBULANG","CARINGIN-GRT","CIBALONG-GRT","CIBATU-GRT","CIBIUK","CIGEDUG","CIHURIP","CIKAJANG","CIKELET","CILAWU","CISEWU","CISOMPET","CISURUPAN","GARUT KOTA","KADUNGORA","KARANGPAWITAN","KARANGTENGAH-GRT","KESARMANAH","LELES-GRT","LEUWIGOONG","MALANGBONG","MEKARMUKTI","PAKENJENG","PAMEUNGPEUK-GRT","PAMULIHAN-GRT","PANGATIKAN","PASIRWANGI","PEUNDEUY","SAMARANG","SELAAWI","SINGAJAYA","SUCINARAJA","SUKARESMI-GRT","SUKAWENING","TALEGONG","TAROGONG KALER","TAROGONG KIDUL","WANARAJA"]);
dsy.add("0_7_13",["ANJATAN","ARAHAN","BALONGAN","BANGODUA","BONGAS","CANTIGI","CIKEDUNG","GABUS WETAN","GANTAR","HAURGEULIS","INDRAMAYU","JATIBARANG-IDM","JUNTINYUAT","KANDANGHAUR","KARANGAMPEL","KEDOKAN BUNDER","KERTASEMAYA","KRANGKENG","KROYA-IDM","LELEA","LOHBENER","LOSARANG","PASEKAN","PATROL","SINDANG-IDM","SLIYEG","SUKAGUMIWANG","SUKRA","TRISI","TUKDANA","WIDASARI"]);
dsy.add("0_7_14",["BANYUSARI","BATUJAYA","CIAMPEL","CIBUAYA","CILAMAYA KULON","CILAMAYA WETAN","CILEBAR","JATISARI","JAYAKERTA","KARAWANG BARAT","KARAWANG TIMUR","KLARI","KOTABARU-KRW","KUTA WALUYA","MAJALAYA-KRW","PAKISJAYA","PANGKALAN","PEDES","PURWASARI","RAWAMERTA","RENGASDENGKLOK","TALAGASARI","TEGALWARU","TELUK JAMBE BARAT","TELUK JAMBE TIMUR","TEMPURAN-KRW","TIRTA JAYA","TIRTA MULYA"]);
dsy.add("0_7_15",["CIAWI GEBANG","CIBEREUM","CIBINGBIN","CIDAHU-KNG","CIGANDAMEKAR","CIGUGUR-KNG","CILEBAK","CILIMUS","CIMAHI","CINIRU","CIPICUNG","CIWARU","DARMA","GARAWANGI","HANTARA","JALAKSANA","JAPARA","KADUGEDE","KALIMANGGIS","KARANGKANCANA","KRAMAT MULYA","KUNINGAN","LEBAKWANGI","LURAGUNG","MALEBER","MANDIRANCAN","NUSAHERANG","PANCALANG","PASAWAHAN-KNG","SELAJAMBE","SIDANGAGUNG","SUBANG-KNG"]);
dsy.add("0_7_16",["ARGAPURA","BANJARAN-MJA","BATURUJEG","CIGASONG","CIKIJING","CINGAMBUL","DAWUAN-MJA","JATI TUJUH","JATIWANGI","KADIPATEN-MJA","KASOKANDEL","KERTAJATI","LEMAHSUGIH","LEUWIMUNDING","LIGUNG","MAJALENGKA","MAJA-MJA","MALAUSMA","PALASAH","PANYINGKIRAN","RAJAGALUH","SINDANG WANGI","SINDANG-MJA","SUKAHAJI","SUMBERJAYA","TALAGA"]);
dsy.add("0_7_17",["BATUJAJAR","CIHAMPELAS","CIKALONG WETAN","CILILIN","CIPATAT","CIPEUNDEUY-NGP","CIPONGKOR","CISARUA-NGP","GUNUNGHALU","LEMBANG-NGP","NGAMPRAH","PADALARANG","PARONGPONG","RONGGA","SAGULING","SINDANGKERTA"]);
dsy.add("0_7_18",["CIGUGUR-PGR","CIJULANG","CIMERAK","KALIPUCANG","LANGKAPLANCAR","MANGUNJAYA","PADAHERANG","PANGANDARAN","PARIGI-PGR","SIDAMULIH"]);
dsy.add("0_7_19",["BANTARGADUNG","BOJONG GENTENG","CIBITUNG-PER","CIEMAS","CIKAKAK","CIKIDANG","CIMANGGU-PER","CIRACAP","CISOLOK","JAMPANG KULON","JAMPANG TENGAH","KALI BUNDER","PALABUHAN PELABUHAN RATU","SIMPENAN","SURADE","TEGAL BULEUD","WALURAN","WARUNG KIARA"]);
dsy.add("0_7_20",["BABAKANCIKAO","BOJONG-PWK","BUNGURSARI-PWK","CAMPAKA-PWK","CIBATU-PWK","DARANGDAN","JATILUHUR","KIARAPEDES","MANIIS","PASAWAHAN-PWK","PLERED-PWK","PONDOK SALAM","PURWAKARTA-PWK","SUKASARI-PWK","SUKATANI-PWK","TEGAL WARU","WANAYASA-PWK"]);
dsy.add("0_7_21",["BANTAR KALONG","BOJONG ASIH","BOJONG GAMBIR","CIAWI-SIN","CIBALONG-SIN","CIGALONTANG","CIKALONG","CIKATOMAS","CINEAM","CIPATUJAH","CISAYONG","CULAMEGA","GUNUNG TANJUNG","JAMANIS","JATIWARAS","KADIPATEN-SIN","KARANG JAYA-SIN","KARANG NUNGGAL","LEUWISARI","MANGUNREJA","MANONJAYA","PADAKEMBANG","PAGERAGEUNG","PANCA TENGAH","PARUNG PONTENG","PUSPAHIANG","RAJAPOLAH","SALAWU","SALOPA","SARIWANGI","SINGAPARNA","SODONGHILIR","SUKAHENING","SUKARAJA-SIN","SUKARAME-SIN","SUKARATU","SUKARESIK","TANJUNGJAYA","TARAJU"]);
dsy.add("0_7_22",["ARJASARI","BALEENDAH","BANJARAN-SOG","BOJONGSOANG","CANGKUANG","CIBEUNYING KIDUL-SOG","CICALENGKA","CIKANCUNG","CILENGKRANG","CILEUNYI","CIMAUNG","CIMEUNYAN","CIPARAY","CIWIDEY","DAYEUHKOLOT","IBUN","KATAPANG","KERTASARI","KUTAWARINGIN","MAJALAYA-SOG","MARGA ASIH","MARGAHAYU","NAGREG","PACET-SOG","PAMEUNGPEUK-SOG","PANGALENGAN","PASEH-SOG","PASIRJAMBU","RANCABALI","RANCAEKEK","SOLOKAN JERUK","SOREANG-SOG"]);
dsy.add("0_7_23",["BINONG","BLANAKAN","CIASEM","CIATER","CIBOGO","CIJAMBE","CIKAUM","CIPEUNDEUY-SBG","CIPUNAGARA","CISALAK","COMPRENG","DAWUAN-SBG","JALANCAGAK","KALIJATI","KASOMALANG","LEGONKULON","PABUARAN-SBG","PAGADEN","PAGADEN BARAT","PAMANUKAN","PATOKBEUSI","PURWADADI-SBG","PUSAKAJAYA","PUSAKANAGARA","SAGALAHERANG","SERANGPANJANG","SUBANG-SBG","SUKASARI-SBG","TAMBAKDAHAN","TANJUNGSIANG"]);
dsy.add("0_7_24",["BAROS-SMI","CARINGIN-SMI","CIAMBAR","CIBADAK-SMI","CIBEUREUM HILIR","CICANTAYAN","CICURUG","CIDADAP-SMI","CIDAHU-SMI","CIDOLOG-SMI","CIKEMBAR","CIKOLE","CIREUNGHAS","CISAAT","CITAMIANG","CURUGKEMBAR","GEGER BITUNG","GUNUNG GURUH","GUNUNG PUYUH","KABANDUNGAN","KADUDAMPIT","KALAPA NUNGGAL","KEBONPEDES","LEMBURSITU","LENGKONG-SMI","NAGRAK","NYALINDUNG","PABUARAN-SMI","PARAKAN SALAK","PARUNG KUDA","PURABAYA","SAGARANTEN","SUKABUMI-SMI","SUKALARANG","SUKARAJA-SMI","WARUDOYONG"]);
dsy.add("0_7_25",["ARJAWINANGUN","ASTANAJAPURA","BABAKAN","BEBER","CILEDUG-SMB","CIWARINGIN","DEPOK-SMB","DUKUPUNTANG","GEBANG-SMB","GEGESIK","GEMPOL","GREGED GREGET","GUNUNG JATI CIREBON UTARA","JAMBLANG","KALIWEDI","KAPETAKAN","KARANGSEMBUNG","KARANGWARENG","KEDAWUNG-SMB","KLANGENAN","LEMAHABANG","LOSARI-SMB","MUNDU","PABEDILAN","PABUARAN-SMB","PALIMANAN","PANGENAN","PANGURAGAN","PASALEMAN","PLERED-SMB","PLUMBON","SEDONG","SUMBER-SMB","SURANENGGALA","SUSUKAN LEBAK","SUSUKAN-SMB","TALUN CIREBON SELATAN","TENGAH TANI","WALED","WERU-SMB"]);
dsy.add("0_7_26",["BUAHDUA","CIBUGEL","CIMALAKA","CIMANGGUNG","CISARUA-SUM","CISITU","CONGGEANG","DARMARAJA","GANEAS","JATIGEDE","JATINANGOR","JATINUNGGAL","PAMULIHAN-SUM","PASEH-SUM","RANCAKALONG","SITURAJA","SUKASARI-SUM","SUMEDANG SELATAN","SUMEDANG UTARA","SURIAN","TANJUNGKERTA","TANJUNGMEDAR","TANJUNGSARI-SUM","TOMO","UJUNG JAYA","WADO"]);
dsy.add("0_7_27",["BUNGURSARI-TSK","CIBEUREUM","CIHIDEUNG","CIPEDES","INDIHIANG","KAWALU","MANGKUBUMI","PURBARATU","TAMANSARI-TSK","TAWANG"]);
dsy.add("0_8",["AMBARAWA","BANJARNEGARA","BANYUMAS","BATANG","BATU","BLORA","BOYOLALI","BREBES","CEPU","CILACAP","DEMAK","GROBOGAN","JEPARA","KAJEN PEKALONGAN","KARANG ANYAR","KEBUMEN","KENDAL","KLATEN","KUDUS","MAGELANG","MUNGKID","PATI","PEKALONGAN","PEMALANG","PURBALINGGA","PURWOREJO","REMBANG","SALATIGA","SEMARANG","SLAWI","SOLO","SRAGEN","SUKOHARJO","TEGAL","TEMANGGUNG","UNGARAN","WONOGIRI","WONOSOBO"]);
dsy.add("0_8_0",["AMBARAWA-AMB","BANYUBIRU","GETASAN","JAMBU","SUMOWONO"]);
dsy.add("0_8_1",["BANJARMANGU","BANJARNEGARA","BATUR","BAWANG-BJN","KALIBENING","KARANGKOBAR","MADUKARA","MANDIRAJA","PANDANDARUM","PEGEDONGAN","PEGENTAN","PEJAWARAN","PUNGGELAN","PURWANEGARA","PURWOREJO KLAMPOK","RAKIT","SIGALUH","SUSUKAN-BJN","WANADADI","WANAYASA-BJN"]);
dsy.add("0_8_2",["AJIBARANG","BANYUMAS-PWO","BATURADEN","CILONGOK","GUMELAR","JATILAWANG","KALIBAGOR","KARANGLEWAS","KEBASEN","KEDUNG BANTENG","KEMRANJEN","KIEMBARAN","LUMBIR","PATIKRAJA","PEKUNCEN","PURWOJATI","PURWOKERTO BARAT","PURWOKERTO SELATAN","PURWOKERTO TIMUR","PURWOKERTO UTARA","RAWALO","SOKARAJA","SOMAGEDE","SUMBANG","SUMPIUH","TAMBAK-PWO","WANGON"]);
dsy.add("0_8_3",["BANDAR-BGG","BANYUPUTIH-BGG","BAWANG-BGG","BLADO","GRINGSING","KANDEMAN","LIMPUNG","PACALUNGAN","REBAN","SUBAH-BGG","TERSONO","TULIS","WARUNGASEM","WONOTUNGGAL"]);
dsy.add("0_8_4",["BATU"]);
dsy.add("0_8_5",["BANJAREJO","BLORA","BOGOREJO","JAPAH","JATI-BOL","JEPON","KUNDURAN","NGAWEN-BOL","TODANAN","TUNJANGAN"]);
dsy.add("0_8_6",["AMPEL","ANDONG","BANYUDONO","BOYOLALI","CEPOGO","JUWANGI","KARANGGEDE","KEMUSU","KLEGO","MOJOSONGO","MUSUK","NGEMPLAK-BYL","NOGOSARI","SAMBI","SAWIT","SELO","SIMO","TERAS","WONOSEGORO"]);
dsy.add("0_8_7",["BANJARHARJO","BANTARKAWUNG","BREBES","BULAKAMBA","BUMIAYU","JATIBARANG-BRB","KERSANA","KETANGGUNAN","LARANGAN-BRB","LOSARI-BRB","PAGUYANGAN","SALEM","SIRAMPOG","SONGGOM","TANJUNG-BRB","TONJONG","WANASARI"]);
dsy.add("0_8_8",["CEPU","JIKEN","KEDUNGTUBAN","KRADENAN-CEU","RANDUBLATUNG","SAMBONG"]);
dsy.add("0_8_9",["ADIPALA","BANTARSARI","BINANGUN-CLP","CILACAP SELATAN","CILACAP TENGAH","CILACAP UTARA","CIMANGGU-CLP","CIPARI","DAYEUHLUHUR","GANDRUNGMANGU","JERUK LEGI","KAMPUNG LAUT","KARANG PUCUNG","KAWUNGANTEN","KEDUNGREJA","KESUGIHAN","KROYA-CLP","MAJENANG","MAOS","NUSAWUNGU","PATIMUAN","SAMPANG-CLP","SIDAREJA","WANAREJA"]);
dsy.add("0_8_10",["BONANG","DEMAK","DEMPET","GAJAH","GUNTUR","KARANG TENGAH-DMK","KARANGANYAR-DMK","KARANGAWEN","KEBONAGUNG-DMK","MIJEN-DMK","MRANGGEN","SAYUNG","WEDUNG","WONOSALAM-DMK"]);
dsy.add("0_8_11",["BRATI","GABUS-PDD","GEYER","GODONG","GROBOGAN","GUBUG","KARANGRAYUNG","KEDUNGJATI","KLAMBU","KRADENAN-PDD","NGARINGAN","PENAWANGAN","PULOKALON","PURWODADI-PDD","TANGGUNGHARJO","TAWANGHARJO","TEGOWANU","TOROH","WIROSARI"]);
dsy.add("0_8_12",["BANGSRI","BATEALIT","DONOREJO","JEPARA","KALING","KALINYAMANTAN","KEDUNG","KEMBANG","MAYONG","MLONGGO","NALUMSARI","PAKIS AJI","PECANGAAN","TAHUNANAN","WELAHAN"]);
dsy.add("0_8_13",["BOJONG-KJN","BUARAN","DORO","KAJEN","KANDANG SERANG","KARANGANYAR-KJN","KARANGDADAP","KEDUNGWUNI","KESESI","LEBAK BARANG","PANINGGARAN","PETUNGKRIONO","SIWALAN","SRAGI-KJN","TALUN-KJN","TIRTO","WIRADESA","WONOKERTO","WONOPRINGGO"]);
dsy.add("0_8_14",["COLOMADU","GONDANGREJO","JATEN","JATIPURO","JATIYOSO","JENAWI","JUMANTONO","JUMAPOLO","KARANG ANYAR","KARANG PANDAN","KEBAK KRAMAT","KERJO","MATESIH","MOJOGEDANG","NGARGOYOSO","TASIKMADU","TAWANGMANGU"]);
dsy.add("0_8_15",["ADIMULYO","ALIYAN","AMBAL","AYAH","BONOROWO","BUAYAN","BULUSPESANTREN","GOMBONG","KARANGANYAR-KBM","KARANGGAYAM","KARANGSAMBUNG","KEBUMEN","KLIRONG","KUTOWINANGUN","KUWARASAN","MIRIT","PADURESO","PEJAGOAN","PETANAHAN","PONCOWARNO","PREMBUN","PURING","ROWOKELE","SADANG","SEMPOR","SRUWENG"]);
dsy.add("0_8_16",["BOJA","BRANGSONG","CEPIRING","GEMUH","KALIWUNGU SELATAN","KALIWUNGU-KNL","KANGKUNG","KENDAL-KNL","LIMBANGAN","NGAMPEL","PAGERRUYUNG","PATEAN","PATEBON","PEGANDON","PLANTUNGAN","RINGGINARUM","ROWOSARI","SINGOOROJO","SUKOREJO-KNL","WELERI"]);
dsy.add("0_8_17",["BAYAT","CAWAS","CEPER","DELANGGU","GANTIWARNO","JATINOM","JOGONALAN","JUWIRING","KALIKOTES","KARANGANOM","KARANGDOWO","KARANGNONGKO","KEBONARUM","KEMALANG","KLATEN SELATAN","KLATEN TENGAH","KLATEN UTARA","MANISRENGGO","NGAWEN-KLT","PEDAN","POLANHARJO","PRAMBANAN-KLT","TRUCUK-KLT","TULUNG","WEDI","WONOSARI-KLT"]);
dsy.add("0_8_18",["BAE","DAWE","GEBOG","JATI-KDS","JEKULO","KALIWUNGU-KDS","KUDUS KOTA","MEJEBO","UNDAAN"]);
dsy.add("0_8_19",["MAGELANG SELATAN","MAGELANG TENGAH","MAGELANG UTARA"]);
dsy.add("0_8_20",["BANDONGAN-MUG","BOROBUDUR-MUG","CANDIMULYO-MUG","DUKUN-MUG","GRABAG-MUG","KAJORAN-MUG","KALIANGKRIK-MUG","MERTOYUDAN-MUG","MUNGKID-MUG","MUNTILAN-MUG","NGABLAK-MUG","NGLUWAR-MUG","PAKIS-MUG","SALAMAN-MUG","SALAM-MUG","SAWANGAN-MUG","SECANG-MUG","SRUMBUNG-MUG","TEGALREJO-MUG","TEMPURAN-MUG","WINDUSARI-MUG"]);
dsy.add("0_8_21",["BATANGAN","CLUWAK","DUKUHSETI","GABUS-PTI","GEMBONG","GUNUNGWUNGKAL","JAKEN","JAKENAN","JUWANA","KAYEN","MARGOREJO","MARGOYOSO","PATI","PUCAKWANGI","SUKOLILO-PTI","TAMBAKROMO","TAYU","TLOGOWUNGU","TRANGKIL","WEDARIJAKSA","WINONG"]);
dsy.add("0_8_22",["PEKALONGAN BARAT","PEKALONGAN SELATAN","PEKALONGAN TIMUR","PEKALONGAN UTARA"]);
dsy.add("0_8_23",["AMPEL GADING","BANTARBOLANG","BELIK","BODEH","COMAL","MOGA","PEMALANG","PETARUKAN","PULOSARI-PML","RANDUDONGKAL","TAMAN-PML","ULUJAMI","WARUNGPRING","WATUKUMPUL"]);
dsy.add("0_8_24",["BOBOTSARI","BOJONGSARI-PUR","BUKATEJA","KALIGONDANG","KALIMANAH","KARANGANYAR-PUR","KARANGJAMBU","KARANGMONCOL","KARANGREJA","KEJOBONG","KEMANGKON","KERTANEGARA","KUTASARI","MREBET","PADAMARA","PENGADEKAN","PURBALINGGA","REMBANG-PUR"]);
dsy.add("0_8_25",["BAGELEN","BANYU URIP","BAYAN-PWJ","BENER","BRUNO","BUTUH","GEBANG-PWJ","GRABAG-PWJ","KALI GESING","KEMIRI-PWJ","KUTOARJO","LOANO","NGOMBOL","PITURUH","PURWODADI-PWJ","PURWOREJO-PWJ"]);
dsy.add("0_8_26",["BULU-RMB","GUNEM","KALIORI","KRAGAN","LASEM","PAMOTAN","PANCUR","REMBANG-RMB","SALE","SARANG","SEDAN","SLUKE","SULANG","SUMBER-RMB"]);
dsy.add("0_8_27",["ARGOMULYO","BANCAK","BRINGIN-SLT","KALIWUNGU-SLT","PABELAN","SIDOMUKTI","SIDOREJO-SLT","SURUH-SLT","SUSUKAN-SLT","TENGARAN","TINGKIR"]);
dsy.add("0_8_28",["BANYUMANIK","CANDISARI","GAJAHMUNGKUR","GAYAMSARI","GENUK","GUNUNGPATI","MIJEN-SRG","NGALIYAN","PEDURUNGAN","SEMARANG BARAT","SEMARANG SELATAN","SEMARANG TENGAH","SEMARANG TIMUR","SEMARANG UTARA","TEMBALANG","TUGU-SRG"]);
dsy.add("0_8_29",["ADIWERNA","BALAPULANG","BOJONG-SWI","BUMIJAWA","DUKUHWARU","JATINEGARA-SWI","KEDUNGBANTENG","KRAMAT","LEBAKSIU","MARGASARI","PAGERBARANG","PANGKAH","SLAWI","SURADADI","TALANG","TARUB","WARUREJA"]);
dsy.add("0_8_30",["BANJARSARI-SOC","JEBRES","LAWEYAN","PASAR KLIWON","SERENGAN","SOLO RAYA"]);
dsy.add("0_8_31",["GEMOLONG","GESI","GONDANG-SRN","JENAR","KALIJAMBE","KARANGMALANG","KEDAWUNG-SRN","MASARAN","MIRI","MONDOKAN","NGAMPAL","PLUPUH","SAMBIREJO","SAMBUNGMACAN","SIDOHARJO-SRN","SRAGEN","SUKODONO-SRN","SUMBERLAWANG","TANGEN","TANON"]);
dsy.add("0_8_32",["BAKI","BENDOSARI","BULU-SUJ","GATAK","GROGOL-SUJ","KARTASURA","MOJOLABAN","NGUTER","POLOKARTO","SUKOHARJO-SUJ","TAWANGSARI","WERU-SUJ"]);
dsy.add("0_8_33",["DUKUHTURI","MARGADANA","TEGAL BARAT","TEGAL SELATAN","TEGAL TIMUR"]);
dsy.add("0_8_34",["BANASARI","BEJEN","BULU-TNU","CANDIROTO","GEMAWANG","JUMO","KALORAN","KANDANGAN-TNU","KEDU","KLEDUNG","KRANGGAN","NGADIREJO","PARAKAN","PRINGSURAT","SELOPAMPANG","TEMANGGUNG","TEMBARAK","TLOGOMULYO","TRETEP","WONOBOYO"]);
dsy.add("0_8_35",["BANDUNGAN","BAWEN","BERGAS","PRINGAPUS","TUNTANG","UNGARAN BARAT","UNGARAN TIMUR"]);
dsy.add("0_8_36",["BATURETNO","BATUWARNO","BULUKERTO","EROMOKO","GIRIMARTO","GIRITRONTO","GIRIWOYO","JATIPURNO","JATIROTO-WGI","JATISRONO","K PUHPELEM","KARANGTENGAH-WGI","KISMANTORO","MANYARAN","NGADIROJO-WGI","NGUNTORONADI-WGI","PARANGGUPITO","PRACIMANTORO","PURWANTORO","SELOGIRI","SIDOHARJO-WGI","SLOGOHIMO","TIRTOMOYO","WONOGIRI","WURYANTORO"]);
dsy.add("0_8_37",["GARUNG","KALIBAWANG-WNB","KALIKAJAR","KALIWIRO","KEJAJAR","KEPIL","KERTEK","LEKSONO","MOJOTENGAH","SAPURAN","SELOMERTO","SUKOHARJO-WNB","WADASLINTANG","WATUMALANG","WONOSOBO-WNB"]);
dsy.add("0_9",["BANGKALAN","BANYUWANGI","BATU","BLITAR","BOJONEGORO","BONDOWOSO","CARUBAN","GRESIK","JEMBER","JOMBANG","KEDIRI","KEPANJEN","LAMONGAN","LUMAJANG","MADIUN","MAGETAN","MALANG","MOJOKERTO","MOJOSARI","NGANJUK","NGASEM","NGAWI","PACITAN","PAITON","PAMEKASAN","PANDAAN","PASURUAN","PONOROGO","PROBOLINGGO","SAMPANG","SIDOARJO","SITUBONDO","SUMENEP","SURABAYA","TRENGGALEK KOTA","TUBAN","TULUNG AGUNG","WLINGI"]);
dsy.add("0_9_0",["BUMIAJI","DAU","JUNREJO","KASEMBON","NGANTANG","ORO ORO OMBO","PUJON"]);
dsy.add("0_9_1",["AROSBAYA","BANGKALAN","BLEGA","BURNEH","GALIS-BWX","GEGER-BWX","KAMAL-BWX","KLAMPIS","KOKOP","KONANG","KWANYAR","LABANG","MODUNG","SEPULU","SOCAH","TANAH MERAH-BWX","TANJUNGBUMI","TRAGAH"]);
dsy.add("0_9_2",["BANGOREJO","BANYUWANGI","CLURING","GAMBIRAN","GENTENG-BWI","GIRI","GLAGAH-BWI","GLENMORE","KABAT","KALIBARU","KALIPURO","LICIN","MUNCAR","PESANGGRAHAN-BWI","PURWOHARJO","ROGOJAMPI","SEMPU","SILIR AGUNG","SINGOJURUH","SONGGON","SRONO","TEGALDIMO","TEGALSARI-BWI","WONGSOREJO"]);
dsy.add("0_9_3",["KEPANJEN KIDUL","REMBANG-BLT","SANAN WETAN","SUKOREJO-BLT"]);
dsy.add("0_9_4",["BALEN","BAURENO","BOJONEGORO","BUBULAN","DANDER","GAYAM-BJE","GONDANG-BJE","KALITIDU","KANOR","KAPAS","KASIMAN","KEDEWAN","KEDUNGADEM","KEPOH BARU","MALO","MARGOMULYO","NGAMBON","NGASEM-BJE","NGRAHO","PADANGAN","PURWOSARI-BJE","SEKAR","SUGIHWARAS","SUKOSEWU","SUMBEREJO-BJE","TAMBAKREJO","TEMAYANG","TRUCUK-BJE"]);
dsy.add("0_9_5",["BINAKAL","BONDOWOSO","BOTO LINGGO","CERMEE","CURAHDAMI","GRUJUGAN","JAMBISARI D S","KELABANG","KEROCOK","MAESAN","PAKEM-BWS","PRAJEKAN","PUJER","SEMPOL","SUKOSARI","SUMBERWRINGIN","TAMANAN","TAPEN","TEGAL AMPEL","TENGGARANG","TLOGOSARI","WONOSARI-BWS","WRINGIN"]);
dsy.add("0_9_6",["BALEREJO","DAGANGAN","DOLOPO","GEGER-CAB","GEMARANG","JIWAN","KARE","KEBONSARI","MADIUN","MEJAYAN","PILANGKENCENG","SARADAN","SAWAHAN-CAB","WONOSARI-CAB","WUNGU"]);
dsy.add("0_9_7",["BALONGPANGGANG","BENJENG","BUNGAH","CERME","DRIYOREJO","DUDUK SAMPEYAN","DUKUN","GRESIK","KEBOMAS","KEDAMEAN","MANYAR","MENGANTI","PANCENG","SANGKAPURA","SIDAYU","TAMBAK-GSK","UJUNG PANGKAH","WRINGIN ANOM"]);
dsy.add("0_9_8",["AJUNG","AMBULU","ARJASA-JBR","BALUNG","BANGSALSARI","GUMUKMAS","JELBUK","JENGGAWAH","JOMBANG-JBR","KALISAT","KALIWATES","KENCONG","LEDOKOMBO","MAYANG","MUMBULSARI","PAKUSARI","PANTI-JBR","PATRANG","PUGER","RAMBIPUJI","SEMBORO","SILO","SUKORAMBI","SUKOWONO","SUMBER BARU","SUMBER JAMBE","SUMBERSARI","TANGGUL","TEMPUREJO","UMBULSARI","WULUHAN"]);
dsy.add("0_9_9",["BANDAR KEDUNG MULYO","BARENG","DIWEK","GUDO","JOGOROTO","JOMBANG-JBG","KABUH","KESAMBEN-JBG","KUDU","MEGALUH","MOJOAGUNG","MOJOWARNO","NGORO-JBG","NGUSIKAN","PERAK","PETERONGAN","PLANDAAN","PLOSO","SUMOBITO","TEMBELANG","WONOSALAM-JBG"]);
dsy.add("0_9_10",["KEDIRI KOTA","MOJOROTO","PESANTREN"]);
dsy.add("0_9_11",["AMPELGADING","BANTUR","BULULAWANG","DAMPIT","DONOMULYO","GEDANGAN-KPJ","GONDANGLEGI","KALIPARE","KEPANJEN","KROMENGAN","NGAJUNG","PAGAK","PAGELARAN-KPJ","PAKISAJI","SUMBERMANJING WETAN","SUMBERPUCUNG","TIRTOYUDO","TUREN","WONOSARI-KPJ"]);
dsy.add("0_9_12",["BABAT","BLULUK","BRONDONG","DEKET","GLAGAH-LMG","KALITENGAH","KARANG GENENG","KARANGBINANGUN","KEDUNGPIRING","KEMBANGBAHU","LAMONGAN","LAREN","MADURAN","MANTUP","MODO","NGIMBANG","PACIRAN","PUCUK","SAMBENG","SARIREJO","SEKARAN","SOLOKURO","SUGIO","SUKODADI","SUKORAME","TIKUNG","TURI-LMG"]);
dsy.add("0_9_13",["CANDIPURO-LMJ","GUCIALIT","JATIROTO-LMJ","KEDUNGJAJANG","KLAKAH","KUNIR","LUMAJANG","PADANG","PASIRIAN","PASRUJAMBE","PROONOJIWO","RANDUAGUNG","RANUYOSO","ROWOKANGKUNG","SENDURO","SUKODONO-LMJ","SUMBERSUKO","TEKUNG","TEMPEH","TEMPURSARI","YOSOWILANGUN"]);
dsy.add("0_9_14",["KARTOHARJO-MDN","MADIUN KOTA","MANGUNHARJO","MANGUNHARJO ANYAR","TAMAN-MDN"]);
dsy.add("0_9_15",["BARAT-MTX","BENDO","KARANGREJO","KARAS-MTX","KARTOHARJO-MTX","KAWEDANAN","LAMBEYAN","MAGETAN","MAOSPATI","NGARIBOYO","NGUNTORONADI-MTX","PANEKAN","PARANG","PLAOSAN","PONCOL","SIDOREJO-MTX","SUKOMORO-MTX","TAKERAN"]);
dsy.add("0_9_16",["BLIMBING","JABUNG-MLG","KARANGPLOSO","KEDUNGKANDANG","KLOJEN","LAWANG","LOWOKWARU","PAKIS-MLG","PONCOKUSUMO","SINGOSARI","SUKUN","TAJINAN","TUMPANG","WAGIR","WAJAK"]);
dsy.add("0_9_17",["DAWAR BLANDONG","DLANGGU","GEDEG","GONDANG-MJK","JATIREJO","JETIS-MJK","KEMLAGI","MAGERSARI","MOJOANYAR","MOJOKERTO KOTA","PRAJURIT KULON","PURI","SOOKO-MJK","TROWULAN"]);
dsy.add("0_9_18",["BANGSAL","KUTOREJO","MOJOSARI","NGORO-MOJ","PACET-MOJ","PUNGGING","TRAWAS"]);
dsy.add("0_9_19",["BAGOR","BARON","BERBEK","GONDANG-NGK","JATIKALEN","KERTOSONO","LENGKONG-NGK","LOCERET","NGANJUK","NGETOS","NGLUYU","NGRONGGOT","PACE","PATIANROWO","PRAMBON-NGK","REJOSO-NGK","SAWAHAN-NGK","SUKOMORO-NGK","TANJUNGANOM","WILANGAN"]);
dsy.add("0_9_20",["BADAS","BANYAKAN","GAMPENGREJO","GROGOL-NGA","GURAH","KANDANGAN-NGA","KANDAT","KAYEN KEDUL","KEPUNG","KRAS","KUNJANG","MOJO","NGADILUWIH","NGANCAR","NGASEM-NGA","PAGU","PAPAR","PARE","PLEMAHAN","PLOSOKLATEN","PUNCU","PURWOSARI-NGA","RINGINREJO","SEMEN","TAROKAN","WATES-NGA"]);
dsy.add("0_9_21",["BRINGIN-NIW","GENENG","GERIH","JOGOROGO","KARANGANYAR-NIW","KARANGJATI","KASREMAN","KEDUNGGALAR","KENDAL-NIW","KWADUNGAN","MANTINGAN","NGAWI","NGRAMBE","PADAS","PANGKUR","PARON","PITU","SINE","WIDODAREN"]);
dsy.add("0_9_22",["ARJOSARI","BANDAR-PCI","DONOROJO","KEBONAGUNG-PCI","NAWANGAN","NGADIROJO-PCI","PACITAN","PRINGKUKU","PUNUNG","SUDIMORO","TEGALOMBO","TULAKAN"]);
dsy.add("0_9_23",["BANTARAN","BANYU ANYAR","BESUK","DRINGU","GADING","GENDING","KOTA ANYAR","KRAKSAAN","KREJENGAN","KRUCIL","KURIPAN-PTN","LECES","LUMBANG-PTN","MARON","PAITON","PAJARAKAN","PAKUNIRAN","SUKAPURA","SUMBERASIH","SUMBER-PTN","TEGAL SIWALAN","TIRIS","TONGAS","WONOMERTO"]);
dsy.add("0_9_24",["BATUMARMAR","GALIS-PKS","KADUR","LARANGAN-PKS","PADEMAWU","PAKONG","PALENGA AN","PAMEKASAN","PASEAN","PEGANTENAN","PROPPO","TLANAKAN","WARU-PKS"]);
dsy.add("0_9_25",["PANDAAN","PRIGEN","PURWODADI-PND","PURWOSARI-PND","SUKOREJO-PND","TUTUR"]);
dsy.add("0_9_26",["BANGIL","BEJI-PSR","BUGULKIDUL","GADING REJO-PSR","GONDANG WETAN","GRATI","KEJAYAN","KRATON-PSR","LEKOK","LUMBANG-PSR","NGULING","PANGGUNGREJO-PSR","PASREPAN","POHJENTREK","PURWOREJO-PSR","PUSPO","REJOSO-PSR","REMBANG-PSR","TOSARI","WINONGAN","WONOREJO"]);
dsy.add("0_9_27",["BABADAN","BADEGAN","BALONG","BUNGKAL","JAMBON","JENANGAN","JETIS-PNO","KAUMAN-PNO","MLARAK","NGEBEL","NGRAYUN","PONOROGO","PUDAK","PULUNG","SAMBIT","SAMPUNG","SAWOO","SIMAN","SLAHUNG","SOOKO-PNO","SUKOREJO-PNO"]);
dsy.add("0_9_28",["KADEMANGAN-PRO","KANIGARAN","KEDOPOK","MAYANGAN","WONOASIH"]);
dsy.add("0_9_29",["BANYUATES","CAMPLONG","JRENGIK","KARANG PENANG","KEDUNGDUNG","KETAPANG-SPG","OMBEN","PANGARENGAN","ROBATAL","SAMPANG-SPG","SOKOBANAH","SRESEH","TAMBELANGAN","TORJUN"]);
dsy.add("0_9_30",["BALONGBENDO","BUDURAN","CANDI","GEDANGAN-SDA","JABON","KREMBUNG","KRIAN","PORONG","PRAMBON-SDA","SEDATI","SIDOARJO","SUKODONO-SDA","TAMAN-SDA","TANGGULANGIN","TARIK","TULANGAN","WARU-SDA","WONOAYU"]);
dsy.add("0_9_31",["ARJASA-SBD","ASEMBAGUS","BANYUGLUGUR","BANYUPUTIH-SBD","BESUKI-SBD","BUNGATAN","JANGKAR","JATIBANTENG","KAPONGAN","KENDIT","MANGARAN","MLANDINGAN","PANARUKAN","PANJI","SITUBONDO","SUBOH","SUMBERMALANG"]);
dsy.add("0_9_32",["AMBUNTEN","ARJASA-SNX","BATANG BATANG","BATUAN","BATUPUTIH","BLUTO","DASUK","DUNGKEK","GANDING","GAPURA","GAYAM-SNX","GILI GINTING","GULUK GULUK","KALIANGET","KANGAYAN","KOTA SUMENEP","LENTENG","MANDING","MASALEMBU","NONGGUNONG","PASONGSONGAN","PRAGAAN","RAAS","RUBARU","SAPEKEN","SARONGGI","TALANGO"]);
dsy.add("0_9_33",["ASEMROWO","BENOWO","BUBUTAN","BULAK","DUKUH PAKIS","GAYUNGAN","GENTENG-SUB","GUBENG","GUNUNGANYAR","JAMBANGAN","KARANGPILANG","KENJERAN","KREMBANGAN","LAKARSANTRI","MULYOREJO","PABEAN CANTIKAN","PAKAL","RUNGKUT","SAMBIKEREP","SAWAHAN-SUB","SEMAMPIR","SIMOKERTO","SUKOLILO-SUB","SUKOMANUNGGAL","TAMBAKSARI-SUB","TANDES","TEGALSARI-SUB","TENGGILIS MEJOYO","WIYUNG","WONOCOLO","WONOKROMO"]);
dsy.add("0_9_34",["BENDUNGAN","DONGKO","DURENAN","GANDUSARI-TGK","KAMPAK","KARANGAN-TGK","MUNJUNGAN","PANGGUL","POGALAN","PULE","SURUH-TGK","TRENGGALEK","TUGU-TGK","WATULIMO"]);
dsy.add("0_9_35",["BANCAR","BANGILAN","GRABAGAN","JATIROGO","JENU","KENDURUAN","KEREK","MERAKURAK","MONTONG","PALANG","PARENGAN","PLUMPANG","RENGAL","SEMANDING","SENORI","SINGGAHAN","SOKO","TAMBAKBOYO","TUBAN","WIDANG"]);
dsy.add("0_9_36",["BANDUNG-TLA","BESUKI-TLA","BONYOLANGU","CAMPUR DARAT","GONDANG-TLA","KALIDAWIR","KARANG REJO","KAUMAN-TLA","KEDUNG WARU","NGANTRU","NGUNUT","PAGERWOJO","PAKEL","PUCANGLABAN","REJOTANGAN","SENDANG","SUMBERGEMPOL","TANGGUNG GUNUNG","TULUNGAGUNG"]);
dsy.add("0_9_37",["BAKUNG","BINANGUN-WLG","DOKO","GANDUSARI-WLG","GARUM","KADEMANGAN-WLG","KANIGORO","KESAMBEN-WLG","NGLEGOK","PANGGUNGREJO-WLG","PONGGOK","SANAN KULON","SELOPURO","SELOREJO","SRENGAT","SUTOJAYAN","TALUN-WLG","UDANAWU","WATES-WLG","WLINGI","WONODADI","WONOTIRTO"]);
dsy.add("0_10",["KUBURAYA","PONTIANAK"]);
dsy.add("0_10_0",["KUBU RAYA","RASAU JAYA","SUNGAI AMBAWANG","SUNGAI KAKAP","SUNGAI RAYA-KUB"]);
dsy.add("0_10_1",["PONTIANAK BARAT","PONTIANAK KOTA","PONTIANAK SELATAN","PONTIANAK TENGGARA","PONTIANAK TIMUR","PONTIANAK UTARA"]);
dsy.add("0_11",["BANJARBARU","BANJARMASIN"]);
dsy.add("0_11_0",["BANJARBARU SELATAN","BANJARBARU UTARA"]);
dsy.add("0_11_1",["BANJARMASIN BARAT","BANJARMASIN SELATAN","BANJARMASIN TENGAH","BANJARMASIN TIMUR","BANJARMASIN UTARA"]);
dsy.add("0_12",["PALANGKARAYA"]);
dsy.add("0_12_0",["JEKAN RAYA","PAHANDUT"]);
dsy.add("0_13",["BALIKPAPAN"]);
dsy.add("0_13_0",["BALIKPAPAN BARAT","BALIKPAPAN KOTA","BALIKPAPAN SELATAN","BALIKPAPAN TENGAH","BALIKPAPAN TIMUR","BALIKPAPAN UTARA"]);
dsy.add("0_14",["BATAM","TANJUNG PINANG"]);
dsy.add("0_14_0",["BATAM KOTA","BATU AJI","BATU AMPAR-BTH","BELAKANG PADANG","BENGKONG","BULANG","GALANG-BTH","LUBUK BAJA","NONGSA","SAGULUNG","SEKUPANG","SUNGAI BEDUK"]);
dsy.add("0_14_1",["BUKIT BESTARI","TANJUNG PINANG BARAT","TANJUNG PINANG KOTA","TANJUNG PINANG TIMUR"]);
dsy.add("0_15",["BANDAR LAMPUNG","LAMPUNG SELATAN","METRO","PRINGSEWU"]);
dsy.add("0_15_0",["BUMI WARAS","ENGGAL","KEDAMAIAN","KEDATON","KEMILING","LABUHAN RATU","LANGKAPURA","PANJANG","RAJABASA-TKG","SUKABUMI-TKG","SUKARAME-TKG","TANJUNG KARANG BARAT","TANJUNG KARANG PUSAT","TANJUNG KARANG TIMUR","TANJUNG SENANG","TELUK BETUNG BARAT","TELUK BETUNG SELATAN","TELUK BETUNG TIMUR","TELUK BETUNG UTARA","WAY HALIM"]);
dsy.add("0_15_1",["BAKAUHENI","CANDIPURO-BKH","JATI AGUNG","KALIANDA","KATIBUNG","KETAPANG-BKH","MERBAU MATARAM","NATAR","PALAS","PANENGAHAN","RAJABASA-BKH","SIDOMULYO","SRAGI-BKH","TANJUNG BINTANG","TANJUNG SARI","WAY PANJI","WAY SULAN"]);
dsy.add("0_15_2",["METRO BARAT","METRO PUSAT","METRO SELATAN","METRO TIMUR","METRO UTARA"]);
dsy.add("0_15_3",["AMBARAWA-PSW","BANYUMAS-PSW","GADING REJO-PSW","PRINGSEWU","SUKOHARJO-PSW"]);
dsy.add("0_16",["BANDA ACEH"]);
dsy.add("0_16_0",["BAITURRAHMAN","BANDA RAYA","JAYA BARU","KUTA ALAM","KUTA RAJA","LUENG BATA","MEURAKSA","SYIAH KUALA","ULEE KARENG"]);
dsy.add("0_17",["BIMA","DOMPU","KAB.BIMA","LOMBOK","MATARAM","SELONG","SUMBAWA BARAT","SUMBAWA BESAR"]);
dsy.add("0_17_0",["ASAKOTA-BMU","MPUNDA-BMU","RABA-BMU","RASANAE BARAT-BMU","RASANAE TIMUR-BMU"]);
dsy.add("0_17_1",["DOMPU","MANGGALEWA","PAJO","WOJA"]);
dsy.add("0_17_2",["SANGGAR","TAMBORA-WHO"]);
dsy.add("0_17_3",["BATU KLIANG","KOPANG","PRAYA","PRAYA TENGAH","PRINGGARATA"]);
dsy.add("0_17_4",["AMPENAN","CAKRANEGARA","GUNUNGSARI-AMI","MATARAM","SANDUBAYA","SEKARBELA","SELAPARANG-AMI"]);
dsy.add("0_17_5",["SELONG"]);
dsy.add("0_17_6",["TALIWANG"]);
dsy.add("0_17_7",["LABUHAN BADAS","SUMBAWA","UNTER IWES"]);
dsy.add("0_18",["BENGKALIS","DUMAI","INDRAGIRI HILIR","INDRAGIRI HULU","PEKANBARU"]);
dsy.add("0_18_0",["BENGKALIS"]);
dsy.add("0_18_1",["DUMAI BARAT","DUMAI KOTA","DUMAI SELATAN","DUMAI TIMUR"]);
dsy.add("0_18_2",["TEMBILAHAN","TEMBILAHAN HULU"]);
dsy.add("0_18_3",["RENGAT"]);
dsy.add("0_18_4",["BUKIT RAYA-PKU","LIMA PULUH","MARPOYAN DAMAI","PAYUNG SEKAKI-PKU","PEKANBARU KOTA","RUMBAI","RUMBAI PESISIR","SAIL","SANAPELAN","SUKAJADI-PKU","TAMPAN","TENAYAN RAYA"]);
dsy.add("0_19",["MAKASSAR"]);
dsy.add("0_19_0",["BIRING KANAYA","BONTOALA","MAKASSAR","MAMAJANG","MANGGALA","MARISO","PANAKKUKANG","RAPPOCINI","TALLO","TAMALANREA","TAMALATE","UJUNG PANDANG","UJUNG TANAH","WAJO"]);
dsy.add("0_20",["BUKIT TINGGI","DHAMASRAYA","LUBUK BASUNG","PADANG","PADANG PANJANG","PADANG PARIAMAN","PARIAMAN","PASAMAN","SAWAH LUNTO","SIJUNJUNG"]);
dsy.add("0_20_0",["AUR BIRUGO TIGO BALEH","GUGUK PANJANG","MANDIANGIN KOTO SELAYAN"]);
dsy.add("0_20_1",["PULAU PUNJUNG"]);
dsy.add("0_20_2",["LUBUK BASUNG"]);
dsy.add("0_20_3",["BUNGUS TELUK KABUNG","KOTO TANGAH","KURANJI-PDG","LUBUK BEGALUNG","LUBUK KILANGAN","NANGGALO","PADANG BARAT","PADANG SELATAN","PADANG TIMUR","PADANG UTARA","PAUH-PDG"]);
dsy.add("0_20_4",["PADANG PANJANG BARAT","PADANG PANJANG TIMUR"]);
dsy.add("0_20_5",["LUBUK ALUNG"]);
dsy.add("0_20_6",["PARIAMAN SELATAN","PARIAMAN TENGAH","PARIAMAN TIMUR","PARIAMAN UTARA"]);
dsy.add("0_20_7",["LUBUK SIKAPING"]);
dsy.add("0_20_8",["BARANGIN","LEMBAH SEGAR","SILUNGKANG","TALAWI-SLU"]);
dsy.add("0_20_9",["SIJUNJUNG"]);
dsy.add("0_21",["BATURAJA","EMPAT LAWANG","KAYU AGUNG","LAHAT","MUARA DUA","MUARA ENIM","OGAN ILIR","OGAN KOMERING ULU TIMUR","PAGAR ALAM","PALEMBANG","PRABUMULIH","SEKAYU"]);
dsy.add("0_21_0",["BATURAJA BARAT","BATURAJA TIMUR"]);
dsy.add("0_21_1",["TEBING TINGGI-TBI"]);
dsy.add("0_21_2",["KAYU AGUNG"]);
dsy.add("0_21_3",["LAHAT"]);
dsy.add("0_21_4",["MUARADUA"]);
dsy.add("0_21_5",["LAWANG KIDUL","MUARA ENIM"]);
dsy.add("0_21_6",["INDRALAYA","INDRALAYA SELATAN","INDRALAYA UTARA"]);
dsy.add("0_21_7",["MARTAPURA"]);
dsy.add("0_21_8",["PAGAR ALAM SELATAN","PAGAR ALAM UTARA"]);
dsy.add("0_21_9",["ALANG-ALANG LEBAR","BUKIT KECIL","GANDUS","ILIR BARAT I","ILIR BARAT II","ILIR TIMUR I","ILIR TIMUR II","KALIDONI","KEMUNING-PLM","KERTAPATI","PLAJU","SAKO","SEBERANG ULU I","SEBERANG ULU II","SEMATANG BORANG","SUKARAME-PLM"]);
dsy.add("0_21_10",["CAMBAI","PRABUMULIH BARAT","PRABUMULIH SELATAN","PRABUMULIH TIMUR","PRABUMULIH UTARA","RAMBANG KAPAK TENGAH"]);
dsy.add("0_21_11",["SEKAYU","SUNGAI LILIN"]);
dsy.add("0_22",["ASAHAN","BATU BARA","BINJAI","DAIRI","DELI SERDANG","GUNUNG SITOLI","HUMBANG HASUNDUTAN","KARO","LUBUK PAKAM","MEDAN","PAKPAK BHARAT","PEMATANG SIANTAR","SAMOSIR","SERDANG BEDAGAI","SIBOLGA","SIPIROK","STABAT","TAPANULI SELATAN","TAPANULI UTARA","TEBING TINGGI","TOBA SAMOSIR"]);
dsy.add("0_22_0",["ASAHAN","KISARAN BARAT KOTA","KISARAN TIMUR KOTA"]);
dsy.add("0_22_1",["LIMAPULUH"]);
dsy.add("0_22_2",["BINJAI BARAT","BINJAI KOTA","BINJAI SELATAN","BINJAI TIMUR","BINJAI UTARA"]);
dsy.add("0_22_3",["SIDIKALANG"]);
dsy.add("0_22_4",["DELI TUA","TANJUNG MORAWA"]);
dsy.add("0_22_5",["GUNUNG SITOLI","GUNUNG SITOLI ALO OA","GUNUNG SITOLI BARAT","GUNUNG SITOLI IDANOI","GUNUNG SITOLI SELATAN","GUNUNG SITOLI UTARA"]);
dsy.add("0_22_6",["DOLOK SANGGUL"]);
dsy.add("0_22_7",["BRASTAGI","KABANJAHE"]);
dsy.add("0_22_8",["BATANG KUIS","GALANG-LBK","LUBUK PAKAM","PANTAI LABU"]);
dsy.add("0_22_9",["AMPLAS","AREA","BARAT-MES","BARU","BELAWAN","DELI","DENAI","HELVETIA","JOHOR","LABUHAN","MAIMUN","MARELAN","MEDAN KOTA","MEDAN TIMUR","PERCUT SEI TUAN","PERJUANGAN","PETISAH","POLONIA","SELAYANG","SUNGGAL-MES","TEMBUNG","TUNTUNGAN"]);
dsy.add("0_22_10",["SALAK"]);
dsy.add("0_22_11",["SIANTAR BARAT","SIANTAR MARIHAT","SIANTAR MARIMBUN","SIANTAR MARTOBA","SIANTAR SELATAN","SIANTAR SITALASARI","SIANTAR TIMUR","SIANTAR UTARA"]);
dsy.add("0_22_12",["PANGURURAN"]);
dsy.add("0_22_13",["SEI RAMPAH"]);
dsy.add("0_22_14",["SIBOLGA KOTA","SIBOLGA SAMBAS","SIBOLGA SELATAN","SIBOLGA UTARA"]);
dsy.add("0_22_15",["SIPIROK"]);
dsy.add("0_22_16",["STABAT"]);
dsy.add("0_22_17",["PADANG SIDEMPUN ANGKOLA JULU","PADANG SIDEMPUN BATUNADUA","PADANG SIDEMPUN HUTAIMBARU","PADANG SIDEMPUN SELATAN","PADANG SIDEMPUN TENGGARA","PADANG SIDEMPUN UTARA"]);
dsy.add("0_22_18",["TARUTUNG"]);
dsy.add("0_22_19",["BAJENIS","PADANG HILIR","PADANG HULU","RAMBUTAN-TTG","TEBING TINGGI-TTG"]);
dsy.add("0_22_20",["BALIGE"]);

dsy.add("0",["BALI","BANGKA BELITUNG","BANTEN","BENGKULU", "D.I. YOGYAKARTA","DKI JAKARTA","JAMBI","JAWA BARAT","JAWA TENGAH","JAWA TIMUR","KALIMANTAN BARAT","KALIMANTAN SELATAN","KALIMANTAN TENGAH","KALIMANTAN TIMUR","KEPULAUAN RIAU","LAMPUNG","NANGGROE ACEH DARUSSALAM","NUSA TENGGARA BARAT","RIAU","SULAWESI SELATAN","SUMATERA BARAT","SUMATERA SELATAN","SUMATERA UTARA"]);


var s=["s_province","s_city","s_county"];//三个select的name
var opt0 = ["Provinsi", "Kota", "Daerah/Kabupaten"];//初始值
function _init_area(){  //初始化函数
    for(i=0;i<s.length-1;i++){
        document.getElementById(s[i]).onchange=new Function("change("+(i+1)+")");
    }
    change(0);
}